########  #######  ########  ########  #### ########  ########  ######## ##    ##       ##      ##  #######  ########  ########   ######  
##       ##     ## ##     ## ##     ##  ##  ##     ## ##     ## ##       ###   ##       ##  ##  ## ##     ## ##     ## ##     ## ##    ## 
##       ##     ## ##     ## ##     ##  ##  ##     ## ##     ## ##       ####  ##       ##  ##  ## ##     ## ##     ## ##     ## ##       
######   ##     ## ########  ########   ##  ##     ## ##     ## ######   ## ## ##       ##  ##  ## ##     ## ########  ##     ##  ######  
##       ##     ## ##   ##   ##     ##  ##  ##     ## ##     ## ##       ##  ####       ##  ##  ## ##     ## ##   ##   ##     ##       ## 
##       ##     ## ##    ##  ##     ##  ##  ##     ## ##     ## ##       ##   ###       ##  ##  ## ##     ## ##    ##  ##     ## ##    ## 
##        #######  ##     ## ########  #### ########  ########  ######## ##    ##        ###  ###   #######  ##     ## ########   ######   
name: ForbiddenWords
version: '${version}'
main: net.juneclaire.forbiddenwords.App
api-version: 1.19
load: STARTUP
author: juneclaire
description: Does shit lmao
website: https://github.com/someoneElse195/PLUGINTHINGY


 ######   #######  ##     ## ##     ##    ###    ##    ## ########   ######  
##    ## ##     ## ###   ### ###   ###   ## ##   ###   ## ##     ## ##    ## 
##       ##     ## #### #### #### ####  ##   ##  ####  ## ##     ## ##       
##       ##     ## ## ### ## ## ### ## ##     ## ## ## ## ##     ##  ######  
##       ##     ## ##     ## ##     ## ######### ##  #### ##     ##       ## 
##    ## ##     ## ##     ## ##     ## ##     ## ##   ### ##     ## ##    ## 
 ######   #######  ##     ## ##     ## ##     ## ##    ## ########   ######  

commands:
  capybara: 
    description: capybara
    usage: /capybara
    permissions: forbiddenwords.killable or forbiddenwords.admin
